server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/study-security?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    tomcat:
      validation-query: SELECT 1 FROM DUAL
  thymeleaf:
    cache: false

mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: com.deallinker.ss.base.entity
  mapper-locations: classpath:mapper/base/*.xml

base:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面的URL
      loginProcessingUrl: /login/form # 登录表单提交处理的url
      usernameParameter: name # 登录表单提交的用户名的属性名
      passwordParameter: pwd  # 登录表单提交的密码的属性名
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: JSON # 认证之后 响应的类型：JSON/REDIRECT
      #  "/code/image","/mobile/page", "/code/mobile"
      imageCodeUrl: /code/image # 获取图形验证码地址
      mobileCodeUrl: /code/mobile # 发送手机验证码地址
      mobilePage: /mobile/page # 前往手机登录页面
      tokenValiditySeconds: 604800 # 记住我功能有效时长
      logoutUrl: /user/logout # 退出请求路径，默认 /logout
      logoutSuccessUrl: /login/page # 退出成功后跳转地址
      deleteCookies: JSESSIONID # 退出后删除什么cookie值
      smsLogin: /sms/login